version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - ENVIRONMENT=development
      - NEO4J_URI=${NEO4J_URI}
      - NEO4J_USER=${NEO4J_USERNAME} 
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - .:/app
      - ./markdown:/app/markdown
      # Persist models directory to avoid re-downloading on every rebuild
      - models_data:/app/models
    networks:
      - app-network

  frontend:
    build: 
      context: ./frontend
      args:
        - REACT_APP_API_BASE_URL=http://backend:8000/api
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  models_data:
    # Named volume for persisting downloaded models
