name: Deploy to AWS EC2 with Docker Compose

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy code to AWS EC2 using Git
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USER }}
        key: ${{ secrets.AWS_SSH_KEY }}
        script: |
          # Create project directory if it doesn't exist
          mkdir -p /home/${{ secrets.AWS_USER }}/memduo
          cd /home/${{ secrets.AWS_USER }}/memduo
          
          # Initialize git repo if it doesn't exist
          if [ ! -d ".git" ]; then
            git init
            git remote add origin https://github.com/${{ github.repository }}.git
          fi
          
          # Fetch latest changes
          git fetch origin
          
          # Reset to latest commit (preserves untracked files like .env, logs, uploads)
          git reset --hard origin/${{ github.ref_name }}
          
          # Clean only tracked files, preserve untracked files
          git clean -fd --exclude='.env' --exclude='logs/' --exclude='uploads/' --exclude='chroma_db/' --exclude='*.log'

    - name: Deploy with Docker Compose on AWS EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USER }}
        key: ${{ secrets.AWS_SSH_KEY }}
        script: |
          cd /home/${{ secrets.AWS_USER }}/memduo
          
          # Check if .env file exists
          if [ ! -f ".env" ]; then
            echo "Error: .env file not found. Please create it manually on the server."
            exit 1
          fi
          
          # Stop existing containers
          docker compose down || true
          
          # Clean up unused images and containers
          docker system prune -f
          
          # Pull latest images and rebuild
          docker compose pull || true
          docker compose up -d --build --force-recreate
          
          # Show running containers
          docker compose ps
          
          # Show logs for debugging
          docker compose logs --tail=50
