name: Deploy to AWS EC2 with Docker Compose

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Copy code to AWS EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USER }}
        key: ${{ secrets.AWS_SSH_KEY }}
        source: "."
        target: "/home/${{ secrets.AWS_USER }}/memduo"
        rm: true

    - name: Deploy with Docker Compose on AWS EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USER }}
        key: ${{ secrets.AWS_SSH_KEY }}
        script: |
          cd /home/${{ secrets.AWS_USER }}/memduo
          
          # Stop existing containers
          docker compose down || true
          
          # Clean up unused images and containers
          docker system prune -f
          
          # Pull latest images and rebuild
          docker compose pull || true
          docker compose up -d --build --force-recreate
          
          # Show running containers
          docker compose ps
          
          # Show logs for debugging
          docker compose logs --tail=50
